/**
 * Generate a pure Python inline polling script (`python3 -c "..."`) that
 * waits for a session to become idle, then fetches and prints the assistant's
 * response. Wrapped in a single-line bash command with PYTHONIOENCODING=utf-8
 * for Windows emoji compatibility.
 *
 * Designed for `Bash(run_in_background=true)` — the OS process exits on completion,
 * timeout, or server disconnection, and the runtime injects a `<notification>`
 * into the coordinating session.
 *
 * Defenses:
 *   - Max N consecutive request failures → exit(2) "server unreachable"
 *   - Max total elapsed per round → round timeout; if the session is still alive,
 *     start a new round (up to max_rounds) instead of giving up (v2.24)
 *   - Max rounds exhausted → exit(3) "timeout"
 *   - Lock file missing after read → exit(4) "lock lost"
 *   - Invalid receipt (rlen < MIN_TEXT) from ANY failure shape — upstream model
 *     error / interrupted / stalled / no-output — auto-inject "继续" (pure counting,
 *     up to 3, short RESUME_GRACE between; regular 2s monitoring resumes at once)
 *     → exhausted → exit(5) + marker file (v2.25)
 *   - Context token threshold exceeded → warning printed but exit(0)
 *
 * Uses `python3` with `python` fallback in the shell wrapper for cross-platform
 * compatibility.
 *
 * Modification history:
 *   2026-08-27 | kimi-code (fix) | v2.25 容错重构：诊断降级为标注用途——移除子串关键词匹配（error/failed/timeout 误命中），改结构化读取 step.end finishReason；除 NORMAL(end_turn) 外一切异常形态统一自动注入"继续"×3——纯计数无观察期（注入间仅 RESUME_GRACE=15s 启动宽限防 POST→busy 竞速连发，session 完工即正常出口），计满才落标记文件 exit 5 回调 PM；另 POLL_SCRIPT 全请求禁用系统代理（Windows 注册表代理开启时回环轮询被路由进外部代理黑洞，实测误报根因）
 *   2026-08-24 | kimi-code (feat) | v2.24 轮询加固：默认超时 300→900s + max_rounds 续轮（存活才续）+ 状态机诊断（空/短回执→查 log→自动"继续"×3→阻塞标记 exit 5）+ lock 一次遍历
 *   2026-08-03 | kimi-code (fix) | poll-result 失败标记：fetch 异常/无文本时写 [POLL_FETCH_FAILED] 覆盖旧文件，防 PM 误读残留（v2.21）
 *   2026-08-03 | kimi-code (fix) | 0.31+ busy 漂移：busy=true 补查详情 main_turn_active 判定主 turn（后台任务不再阻塞轮询；v2.21）
 *   2026-07-24 | kimi-code (fix) | 0.28+ 兼容：lock 路径 server/lock → server/instances/*.json 双格式，5 次重试遍历全部路径
 *   2026-07-20 | kimi-code (fix) | 0.24+ 适配：status 枚举 → busy/pending_interaction 双模型判定，消除 SERVER_OFFLINE 误报；busy=False 补查 pending_interaction 防审批中间态提前退出
 *   2026-07-16 | kimi-code (feat) | v2.16 预置脚本 + 降级：POLL_SCRIPT 常量、existsSync 短命令分支、fetch_result 写入 poll-result-{sid}.txt；路径规范化 \→/
 *   2026-07-16 | kimi-code (fix) | Bash→Python 重写：消除 node 依赖、LOCK_LOST 重试、退出码扩展 0/2/3/4
 *   2026-07-16 | kimi-code (feat) | v2.14 新增 parse_context() + CTX_HIGH 阈值检测
 *   2026-07-16 | kimi-code (feat) | 提取 POLL_SCRIPT 常量 + existsSync 文件检测分支（预置脚本优先）
 */

import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { detectKimiServerUrl } from "./server-lock.js";

export interface PollConfig {
  sessionId: string;
  baseUrl?: string;
  token?: string;
  maxWaitSeconds?: number;   // per-round timeout, default 900 (v2.24: 300→900)
  maxFailures?: number;       // consecutive curl failures to abort, default 3
  maxRounds?: number;         // poll rounds on timeout while session alive, default 2 (v2.24)
}

export const POLL_SCRIPT = [
  "import sys, json, os, time, urllib.request",
  "sys.stdout.reconfigure(encoding='utf-8')",
  "",
  "sid = sys.argv[1]",
  "base_url = sys.argv[2] if sys.argv[2] != 'default' else ''",
  "token = sys.argv[3] if sys.argv[3] != 'default' else ''",
  "max_sec = int(sys.argv[4]) if len(sys.argv) > 4 else 900",
  "max_fails = int(sys.argv[5]) if len(sys.argv) > 5 else 3",
  "max_rounds = int(sys.argv[6]) if len(sys.argv) > 6 else 2",
  "",
  "# ---- read lock once (v2.24: read-only port hint, no retries) ----",
  "server_dir = os.path.expanduser('~/.kimi-code/server')",
  "",
  "# helper: try to read port from a lock file, return port or None",
  "def try_lock(path):",
  "    try:",
  "        return json.load(open(path)).get('port')",
  "    except Exception:",
  "        return None",
  "",
  "# build lock path list: legacy server/lock first, then server/instances/*.json",
  "def get_lock_paths():",
  "    paths = [os.path.join(server_dir, 'lock')]  # legacy (<0.28)",
  "    inst = os.path.join(server_dir, 'instances')",
  "    if os.path.isdir(inst):",
  "        for f in sorted(os.listdir(inst)):",
  "            if f.endswith('.json'):",
  "                paths.append(os.path.join(inst, f))",
  "    return paths",
  "",
  "port = None",
  "for p in get_lock_paths():",
  "    port = try_lock(p)",
  "    if port:",
  "        break",
  "",
  "if not port:",
  "    print(f'[LOCK_LOST] 未检测到 Kimi Server（已检查 {len(get_lock_paths())} 个实例文件）——tunnel 将自动激活，可稍后重试')",
  "    sys.exit(4)",
  "",
  "if not base_url:",
  "    base_url = f'http://127.0.0.1:{port}'",
  "",
  "# ---- build auth header helper ----",
  "# v2.25: 本机服务禁用一切系统代理（注册表/env），防 Windows 代理开启时回环请求被路由进外部代理黑洞",
  "urllib.request.install_opener(urllib.request.build_opener(urllib.request.ProxyHandler({})))",
  "",
  "def make_req(path):",
  "    req = urllib.request.Request(f'{base_url}{path}')",
  "    if token:",
  "        req.add_header('Authorization', f'Bearer {token}')",
  "    return req",
  "",
  "# ---- context threshold reader ----",
  "def read_ctx_threshold():",
  "    th_path = os.path.expanduser('~/.kimi-tunnel/ctx-threshold')",
  "    try:",
  "        return int(open(th_path).read().strip())",
  "    except:",
  "        return 36000",
  "",
  "# ---- fetch assistant reply ----",
  "def fetch_result():",
  "    result_path = os.path.expanduser(f'~/.kimi-tunnel/poll-result-{sid}.txt')",
  "    def mark_failed(reason):",
  "        # 失败标记覆盖旧文件，防 PM 误读上次残留结果（v2.21）",
  "        try:",
  "            with open(result_path, 'w', encoding='utf-8') as f:",
  "                f.write('[POLL_FETCH_FAILED] %s @ %s\\n' % (reason, time.strftime('%Y-%m-%dT%H:%M:%S')))",
  "        except Exception:",
  "            pass",
  "    try:",
  "        req = make_req(f'/api/v1/sessions/{sid}/messages?page_size=1&role=assistant')",
  "        data = json.load(urllib.request.urlopen(req, timeout=10))",
  "        for m in data.get('data', {}).get('items', []):",
  "            for b in m.get('content', []):",
  "                if b.get('type') == 'text' and b.get('text'):",
  "                    text = b['text']",
  "                    print(text)",
  "                    # Write to fixed path for PM quick-read (sid isolates parallel sessions)",
  "                    try:",
  "                        with open(result_path, 'w', encoding='utf-8') as f:",
  "                            f.write(text)",
  "                    except Exception:",
  "                        pass",
  "                    return len(text)  # v2.24: return length for short-reply diagnosis",
  "        mark_failed('no text block in latest assistant message')",
  "    except Exception as e:",
  "        print(f'[fetch_result] {e}')",
  "        mark_failed(str(e))",
  "    return 0",
  "",
  "# ---- blocked-session diagnosis (v2.25: label-only; unified auto-continue recovery) ----",
  "def env_int(name, default):",
  "    try:",
  "        return int(os.environ.get(name, default))",
  "    except Exception:",
  "        return default",
  "",
  "MIN_TEXT = env_int('KIMI_POLL_MIN_TEXT', 20)",
  "STALL_SEC = env_int('KIMI_POLL_STALL_SEC', 120)",
  "RESUME_GRACE = env_int('KIMI_POLL_RESUME_GRACE', 15)  # 注入后的启动宽限：等 POST 生效转 busy，非观察期",
  "marker_path = os.path.expanduser(f'~/.kimi-tunnel/poll-blocked-{sid}.md')",
  "retry_continue = 0",
  "",
  "def find_wire_log():",
  "    import glob as _glob",
  "    base = os.path.expanduser('~/.kimi-code/sessions')",
  "    cand = _glob.glob(os.path.join(base, 'wd_*', sid, 'agents', 'main', 'wire.jsonl'))",
  "    return cand[0] if cand else None",
  "",
  "def diagnose_blocked():",
  "    \"\"\"Inspect wire.jsonl tail; return (kind, reason).",
  "",
  "    v2.25: kind 仅作标注/记录用，不再拦截恢复流程——除 NORMAL(end_turn 正常完成)",
  "    外的一切异常形态统一由主循环自动注入\"继续\"×3。判定基于结构化的",
  "    step.end finishReason 字段，不做任何文本子串匹配，避免工具参数、文件名、",
  "    错误文案误命中（v2.24 实测：上游报错形态被 ERROR 子串分支短路吞掉）。",
  "    \"\"\"",
  "    wire = find_wire_log()",
  "    if not wire:",
  "        return ('NO_LOG', 'wire.jsonl not found')",
  "    try:",
  "        raw = open(wire, encoding='utf-8', errors='replace').read()",
  "    except Exception as e:",
  "        return ('NO_LOG', f'cannot read wire log: {e}')",
  "    tail = [l for l in raw.splitlines() if l.strip()][-50:]",
  "    if not tail:",
  "        return ('NO_LOG', 'wire log tail empty')",
  "    last_ts = 0",
  "    has_end_turn = False",
  "    has_image = False",
  "    recent_error = False   # any step.end finishReason='error' in window",
  "    last_fin = ''          # finishReason of the LAST step.end",
  "    for l in tail:",
  "        try:",
  "            e = json.loads(l)",
  "        except Exception:",
  "            continue",
  "        ts = e.get('time') or 0",
  "        if ts:",
  "            last_ts = max(last_ts, ts)",
  "        s = json.dumps(e, ensure_ascii=False).lower()",
  "        if 'image' in s or '图片' in s:",
  "            has_image = True",
  "        if e.get('type') == 'context.append_loop_event':",
  "            ev = e.get('event', {})",
  "            if ev.get('type') == 'step.end':",
  "                fin = str(ev.get('finishReason') or '')",
  "                last_fin = fin",
  "                if fin == 'error':",
  "                    recent_error = True",
  "                elif fin == 'end_turn':",
  "                    has_end_turn = True",
  "    stalled = int(time.time() - last_ts)",
  "    if has_end_turn:",
  "        return ('NORMAL', 'turn completed (end_turn) — short/empty reply is a tool-only turn')",
  "    # 上游模型请求失败是主要故障源（provider 临时不稳定），结构性识别即可，无需细分错误种类",
  "    if recent_error:",
  "        return ('UPSTREAM_ERROR', f'last step.end={last_fin or \"?\"} — model request failed within window ({stalled}s ago)')",
  "    if last_fin == 'interrupted':",
  "        return ('INTERRUPTED', 'last turn interrupted — no text reply produced')",
  "    if stalled > STALL_SEC:",
  "        if has_image:",
  "            return ('IMAGE_BLOCK', f'stalled {stalled}s with image content — model may lack multimodal support')",
  "        return ('MODEL_TIMEOUT', f'stalled {stalled}s without output')",
  "    return ('NO_OUTPUT', f'idle without end_turn, last event {stalled}s ago (<{STALL_SEC}s)')",
  "",
  "def write_block_marker(kind, reason, detail=''):",
  "    try:",
  "        with open(marker_path, 'w', encoding='utf-8') as f:",
  "            f.write('# Poll Blocked Marker\\n')",
  "            f.write(f'- time: {time.strftime(\"%Y-%m-%dT%H:%M:%S\")}\\n')",
  "            f.write(f'- session: {sid}\\n')",
  "            f.write(f'- kind: {kind}\\n')",
  "            f.write(f'- reason: {reason}\\n')",
  "            if detail:",
  "                f.write(f'- detail: {detail}\\n')",
  "            if kind == 'IMAGE_BLOCK':",
  "                f.write('- action: 疑似读图阻塞——已自动注入\"继续\"3 次仍无产出，建议另起 session，勿再投图\\n')",
  "            else:",
  "                f.write('- action: 异常未恢复——已自动注入\"继续\"3 次仍无有效产出，建议 PM 用 read_session_log 查看详情后决定重试或退役\\n')",
  "    except Exception:",
  "        pass",
  "",
  "# ---- main polling loop ----",
  "start_ts = time.time()",
  "fails = 0",
  "round_no = 0",
  "status_ok = False  # v2.24: whether the last status request succeeded (round-continuation check)",
  "while True:",
  "    elapsed = int(time.time() - start_ts)",
  "",
  "    # Guard: per-round timeout → continue to next round if session alive (v2.24)",
  "    if elapsed >= max_sec:",
  "        if round_no < max_rounds and status_ok and status not in ('idle', 'aborted'):",
  "            round_no += 1",
  "            start_ts = time.time()",
  "            print(f'[POLL_ROUND {round_no}/{max_rounds}] 等待 {max_sec}s 超时但 session 存活，进入下一轮')",
  "            continue",
  "        print(f'[POLL_TIMEOUT] 等待 {max_sec}s 超时（{round_no}/{max_rounds} 轮），session 可能卡住或 server 离线')",
  "        fetch_result()",
  "        sys.exit(3)",
  "",
  "    # Poll session status",
  "    status = ''",
  "    ctx_tokens = ''",
  "    ctx_max = ''",
  "    try:",
  "        req = make_req(f'/api/v1/sessions/{sid}/status')",
  "        d = json.load(urllib.request.urlopen(req, timeout=10))",
  "        sdata = d.get('data', {})",
  "        # 双模型兼容: 0.22.x status 枚举优先; 0.24+ 按 busy 推导（见 API.md §五）",
  "        if sdata.get('status'):",
  "            status = sdata['status']",
  "        elif sdata.get('busy') is True:",
  "            # 0.31+ 实测：busy 含后台任务/持续活动（turn 结束后仍可能为 true），主 turn 判定补查详情",
  "            # （pending_interaction 优先于 main_turn_active，与 wire-client getSessionStatus 同策略）",
  "            status = 'running'",
  "            try:",
  "                req2 = make_req(f'/api/v1/sessions/{sid}')",
  "                d2 = json.load(urllib.request.urlopen(req2, timeout=10))",
  "                d2data = d2.get('data', {})",
  "                pi = d2data.get('pending_interaction', 'none')",
  "                if pi == 'approval':",
  "                    status = 'awaiting_approval'",
  "                elif pi == 'question':",
  "                    status = 'awaiting_question'",
  "                elif d2data.get('main_turn_active') is False:",
  "                    status = 'idle'",
  "            except Exception:",
  "                pass",
  "        elif sdata.get('busy') is False:",
  "            status = 'idle'",
  "            # 0.24+ 补查 pending_interaction: approval/question 暂停时 busy=false 但 turn 未完结",
  "            # （与 wire-client getSessionStatus 同一策略；取值 approval/question 为推断，未命中则保持 idle 兜底）",
  "            try:",
  "                req2 = make_req(f'/api/v1/sessions/{sid}')",
  "                d2 = json.load(urllib.request.urlopen(req2, timeout=10))",
  "                pi = d2.get('data', {}).get('pending_interaction', 'none')",
  "                if pi == 'approval':",
  "                    status = 'awaiting_approval'",
  "                elif pi == 'question':",
  "                    status = 'awaiting_question'",
  "            except Exception:",
  "                pass",
  "        ctx_tokens = sdata.get('context_tokens', '')",
  "        ctx_max = sdata.get('max_context_tokens', '')",
  "        status_ok = True  # v2.24: request succeeded — session reachable",
  "    except Exception:",
  "        pass",
  "",
  "    # Guard: server unreachable (empty status)",
  "    if not status:",
  "        fails += 1",
  "        if fails >= max_fails:",
  "            print(f'[SERVER_OFFLINE] 连续 {fails} 次请求失败，Kimi Server 可能已离线')",
  "            sys.exit(2)",
  "        time.sleep(3)",
  "        continue",
  "",
  "    fails = 0  # reset on success",
  "",
  "    if status in ('idle', 'aborted'):",
  "        # Context token check",
  "        if ctx_tokens:",
  "            try:",
  "                threshold = read_ctx_threshold()",
  "                if int(ctx_tokens) > threshold:",
  "                    cm = ctx_max or '?'",
  "                    print(f'[CTX_HIGH] {ctx_tokens} / {cm} tokens（阈值: {threshold}）— 建议 PM 评估退役')",
  "            except:",
  "                pass",
  "        print('---RESULT---')",
  "        rlen = fetch_result()",
  "        # v2.25: 空/极短回执 → 无差别容错。除 NORMAL(end_turn 工具型回合)外，",
  "        # 一切异常形态（上游报错/中断/停滞/读图/无输出）统一自动注入\"继续\"并续监，",
  "        # 连续 3 次无效才落标记文件并 exit 5 回调 PM",
  "        if rlen < MIN_TEXT:",
  "            print(f'[POLL_DIAG] 回执长度 {rlen} 低于阈值 {MIN_TEXT}，检测 session 日志状态...')",
  "            kind, reason = diagnose_blocked()",
  "            print(f'[POLL_DIAG] 判定: {kind} — {reason}')",
  "            if kind == 'NORMAL':",
  "                pass  # turn 正常结束（工具型回合无文本属预期），不干预",
  "            elif retry_continue >= 3:",
  "                write_block_marker(kind, reason, f'continue-sent={retry_continue}')",
  "                print(f'[POLL_BLOCKED] 自动注入\"继续\" {retry_continue} 次后仍无有效产出（{kind}: {reason}），请 PM 介入（标记: {marker_path}）')",
  "                sys.exit(5)",
  "            else:",
  "                retry_continue += 1",
  "                try:",
  "                    req = make_req(f'/api/v1/sessions/{sid}/prompts')",
  "                    req.add_header('Content-Type', 'application/json')",
  "                    body = json.dumps({'content': [{'type': 'text', 'text': '继续'}]}).encode('utf-8')",
  "                    urllib.request.urlopen(req, data=body, timeout=10)",
  "                    print(f'[POLL_DIAG] 异常({kind})：已自动注入\"继续\"（{retry_continue}/3），{RESUME_GRACE}s 启动宽限后回归常规监测...')",
  "                except Exception as e:",
  "                    print(f'[POLL_DIAG] 发送\"继续\"失败: {e}')",
  "                # v2.25 精简：无观察期。宽限仅为防「POST 与 turn 转busy 的竞速」导致 idle 残留态连发击穿；",
  "                # 之后回到主循环按正常节奏监测——session 若完工即走正常出口，计数满 3 才落标记",
  "                time.sleep(RESUME_GRACE)",
  "                continue",
  "        sys.exit(0)",
  "",
  "    time.sleep(2)",
].join("\n");

export function generatePollCommand(config: PollConfig): string {
  const { sessionId, token = "", maxWaitSeconds = 900, maxFailures = 3 } = config;
  const maxRounds = config.maxRounds ?? parseInt(process.env.KIMI_POLL_MAX_ROUNDS || "2", 10);
  const baseUrl = config.baseUrl || process.env.KIMI_SERVER_URL || detectKimiServerUrl();
  const effectiveToken = token || process.env.KIMI_SERVER_TOKEN || "";
  const safe = (v: string) => v.includes(" ") ? `"${v}"` : v;
  const args = `${safe(sessionId)} ${safe(baseUrl || "default")} ${safe(effectiveToken || "default")} ${maxWaitSeconds} ${maxFailures} ${maxRounds}`;

  const pollPyPath = `${homedir()}/.kimi-tunnel/poll.py`.replace(/\\/g, "/");

  if (existsSync(pollPyPath)) {
    // Prebuilt script available — short command
    return [
      `PYTHONIOENCODING=utf-8 python3 ${pollPyPath} ${args} 2>/dev/null`,
      `|| python ${pollPyPath} ${args}`,
    ].join(" \\\n   ");
  }

  // Degraded: inline full script
  const pyEncoded = POLL_SCRIPT.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const pythonLine = `python3 -c "${pyEncoded}" ${args}`;
  return [
    `PYTHONIOENCODING=utf-8 ${pythonLine} 2>/dev/null`,
    `|| ${pythonLine}`,
  ].join(" \\\n   ");
}
